version: "3.8"

services:
  backend:
    build: ./backend
    container_name: tatacliq-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: tatacliq-frontend
    ports:
      - "3006:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: tatacliq-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

