import React from 'react';
import Footer from '../components/Footer';

export default function Terms() {
  return (
    <div className="container mx-auto px-4 py-8">
      {/* Page Title */}
      <h2 className="text-3xl font-bold text-center mb-6">We’re a Movement Beyond Style</h2>

      {/* Introduction */}
      <section className="mb-6">
        <p>
          These policies are published in accordance with the provisions of Rule 3(1) of the 
          Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021, 
          and are an ‘electronic record’ as contemplated under section 2(t) of the Information Technology Act, 2000 and the Rules thereunder. 
          These Terms being an electronic record are generated by a computer system and do not require any physical or digital signatures.
        </p>
      </section>

      {/* Access to the App */}
      <section className="mb-6">
        <h3 className="text-2xl font-semibold mb-2">ACCESS TO THE APP</h3>
        <p>
          The App is owned by Tata UniStore Limited having registered office at 4th Floor, Empire Plaza 2, 
          Chandan Nagar, LBS Marg, Vikhroli (W), Mumbai - 400083 (Tata CLiQ Fashion).
        </p>
        <p>
          Use of the App by the user (“You” / “User”) is subject to the terms and conditions contained herein. 
          Accessing, browsing or otherwise using the App will be construed as Your unequivocal and irrevocable 
          acceptance and acknowledgement of the Terms of Use and policies hereof.
        </p>
        <p>
          By using the App, You declare to have carefully read, understood, and agree to be bound by these Terms of Use.
          Tata CLiQ Fashion may at its sole discretion allow or disallow access to the App and reserves the right 
          to change any of the terms and conditions at any time. It is Your responsibility to periodically review these 
          Terms of Use, and Your continued use of the App will be considered Your acceptance of any updates and changes.
        </p>
      </section>

      {/* Eligibility */}
      <section className="mb-6">
        <h3 className="text-2xl font-semibold mb-2">ELIGIBILITY</h3>
        <p>
          You should be at least 18 years of age and competent to enter into a contract under Indian contract law. 
          If You are under 18 years and wish to use the App, it must be through a legal guardian in accordance with applicable law.
        </p>
        <p>
          If You are using the App on behalf of any company, institution, or other entity, You must be authorized to act on its behalf.
        </p>
        <p>
          Tata CLiQ Fashion reserves the right to refuse or terminate access to any user at any time without providing any reason.
        </p>
      </section>

      {/* Compliance Requirements */}
      <section className="mb-6">
        <h3 className="text-2xl font-semibold mb-2">COMPLIANCE REQUIREMENTS</h3>
        <p>
          Every User shall comply with all applicable laws, including but not limited to:
        </p>
        <ul className="list-disc list-inside ml-4">
          <li>Foreign Exchange Management Act, 1999</li>
          <li>Exchange Control Manual issued by the Reserve Bank of India</li>
          <li>Customs Act, 1962</li>
          <li>Information Technology Act, 2000</li>
          <li>Prevention of Money Laundering Act, 2002</li>
          <li>Foreign Contribution Regulation Act, 1976</li>
          <li>Income Tax Act, 1961</li>
          <li>Export Import Policy of the Government of India</li>
        </ul>
        <p>
          This includes all related amendments, notifications, and rules as applicable when using the App 
          or purchasing/selling any product or service through the App.
        </p>
      </section>

      <Footer />
    </div>
  );
}

